### ISSUE TITLE
Write a CRC32 string parser

### ISSUE THREAD

**Issue by robotoshi** [CalgaryToSpace/CTS-SAT-1-OBC-Firmware#77] opened 2024-06-28 00:35 UTC
Write a function that takes in a CRC32 string and returns the binary representation.

**Comment by DeflateAwning** [comment] 2024-07-06 17:38
Is a duplicate of #89

**Comment by DeflateAwning** [comment] 2024-07-06 17:38
Is a duplicate of https://github.com/CalgaryToSpace/CTS-SAT-1-OBC-Firmware/issues/89

**Closed by DeflateAwning** 2024-07-06 17:38 UTC
Labels: good first issue
